# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce6266e67c338004ee0fc6dc115e838fb4df644e0ee75e094813fa8b0c56428271b3b9f526da6a593bbf7eea6eb4acd0c9ef80955b98d0ada33637308e917876

test:
  secret_key_base: 365d0e875439d693b9e1b0ac7210cfaa03c5f93f1fa3693255e0bd0ee185b15a78d8007c085bf9b2f1ba45fb2131caa87732fc23020618bafc1f75ed08048c3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
